
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
// Implementasi class turunan Drinks_Shop ( modul 6) 
public class Drinks_Shop extends javax.swing.JFrame {
    /**
     * Creates new form Drinks_Shop
     */
    public Drinks_Shop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NamaTxt = new javax.swing.JTextField();
        PilihMejaCbx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        DineInCb = new javax.swing.JCheckBox();
        TakeAwayCb = new javax.swing.JCheckBox();
        MatchaCb = new javax.swing.JCheckBox();
        OreoCb = new javax.swing.JCheckBox();
        VanillaCb = new javax.swing.JCheckBox();
        StrawberryCb = new javax.swing.JCheckBox();
        CoklatCb = new javax.swing.JCheckBox();
        ManggaCb = new javax.swing.JCheckBox();
        Jmlh2Txt = new javax.swing.JTextField();
        Jmlh1Txt = new javax.swing.JTextField();
        Jmlh3Txt = new javax.swing.JTextField();
        Jmlh5Txt = new javax.swing.JTextField();
        Jmlh4Txt = new javax.swing.JTextField();
        Jmlh6Txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DRINK ME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pemesan :");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Nomor Meja     :");

        NamaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaTxtActionPerformed(evt);
            }
        });

        PilihMejaCbx.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        PilihMejaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Meja", "Meja 1", "Meja 2", "Meja 3", "Meja 4", "_" }));
        PilihMejaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihMejaCbxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu Minuman");

        DineInCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DineInCb.setText("Dine In");
        DineInCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInCbActionPerformed(evt);
            }
        });

        TakeAwayCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TakeAwayCb.setText("Take Away");
        TakeAwayCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeAwayCbActionPerformed(evt);
            }
        });

        MatchaCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        MatchaCb.setText("Matcha");
        MatchaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchaCbActionPerformed(evt);
            }
        });

        OreoCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        OreoCb.setText("Oreo");
        OreoCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OreoCbActionPerformed(evt);
            }
        });

        VanillaCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        VanillaCb.setText("Vanilla");
        VanillaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanillaCbActionPerformed(evt);
            }
        });

        StrawberryCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        StrawberryCb.setText("Strawberry");
        StrawberryCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrawberryCbActionPerformed(evt);
            }
        });

        CoklatCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        CoklatCb.setText("Coklat");
        CoklatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoklatCbActionPerformed(evt);
            }
        });

        ManggaCb.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        ManggaCb.setText("Mangga");
        ManggaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManggaCbActionPerformed(evt);
            }
        });

        Jmlh2Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh2Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Jmlh1Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh1Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Jmlh3Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh3Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Jmlh5Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh5Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Jmlh4Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh4Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Jmlh6Txt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Jmlh6Txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Jumlah");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Minuman Yang Dipesan :");

        OutputTxt.setColumns(20);
        OutputTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        OutputTxt.setRows(5);
        jScrollPane1.setViewportView(OutputTxt);

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("Pesan ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rasa");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Harga");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rasa");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Harga");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("15K");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("15K");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("10K");

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("20K");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("12K");

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("10K");

        jButton3.setBackground(new java.awt.Color(51, 255, 0));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setText("Okee");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PilihMejaCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(DineInCb)
                                .addGap(61, 61, 61)
                                .addComponent(TakeAwayCb)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MatchaCb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(Jmlh1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Jmlh3Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Jmlh2Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StrawberryCb)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(OreoCb))
                                            .addComponent(ManggaCb))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jmlh4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Jmlh5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Jmlh6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CoklatCb)
                                    .addComponent(VanillaCb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OreoCb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(Jmlh4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Jmlh5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MatchaCb)
                                        .addComponent(jLabel15))
                                    .addComponent(Jmlh1Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PilihMejaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VanillaCb)
                            .addComponent(Jmlh2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StrawberryCb)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TakeAwayCb)
                    .addComponent(DineInCb)
                    .addComponent(CoklatCb)
                    .addComponent(Jmlh3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManggaCb)
                    .addComponent(Jmlh6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaTxtActionPerformed
    
    private void PilihMejaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihMejaCbxActionPerformed
        // Implementasi switch case ( modul 2)
        switch (PilihMejaCbx.getSelectedIndex()){
            case 0:
                DineInCb.setSelected(true);
                break;
            case 1:
                DineInCb.setSelected(true);
                break;
            case 2:
                DineInCb.setSelected(true);
                break;
            case 3:
                DineInCb.setSelected(true);
                break;
            case 4:
                DineInCb.setSelected(true);
                break;
            default:
                DineInCb.setSelected(false);
                break;
        }
    }//GEN-LAST:event_PilihMejaCbxActionPerformed

    private void CoklatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoklatCbActionPerformed
       
    }//GEN-LAST:event_CoklatCbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NamaTxt.setText("");
        PilihMejaCbx.setSelectedIndex(0);
        DineInCb.setSelected(false);
        TakeAwayCb.setSelected(false);
        MatchaCb.setSelected(false);
        VanillaCb.setSelected(false);
        CoklatCb.setSelected(false);
        OreoCb.setSelected(false);
        StrawberryCb.setSelected(false);
        ManggaCb.setSelected(false);
        Jmlh1Txt.setText("");
        Jmlh2Txt.setText("");
        Jmlh3Txt.setText("");
        Jmlh4Txt.setText("");
        Jmlh5Txt.setText("");
        Jmlh6Txt.setText("");
        OutputTxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TakeAwayCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeAwayCbActionPerformed

        if(TakeAwayCb.isSelected()){
            PilihMejaCbx.setSelectedIndex(5);
            DineInCb.setSelected(false);
        }
    }//GEN-LAST:event_TakeAwayCbActionPerformed
    // Implementasi function privat void ( modul 4)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(NamaTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Nama Pemesan Belum Diisi");
        } else {
            // Pendeklarasian variabel output tipe string (modul 1)
        String output = "Nama: " + NamaTxt.getText() + "\n";
        
        if (DineInCb.isSelected()) {
            output += "Jenis Pesanan: Dine-In\n";
            output += "Meja: " + PilihMejaCbx.getSelectedItem() + "\n";
        } else if (TakeAwayCb.isSelected()) {
            output += "Jenis Pesanan: Take Away\n";
        }
        
        output += "Minuman yang Dipesan:\n";
        if (MatchaCb.isSelected()) {
            output += "- Matcha, Harga: " + (Integer.parseInt(Jmlh1Txt.getText()) * 20000) + "\n";
        }
        if (VanillaCb.isSelected()) {
            output += "- Vanilla, Harga: " + (Integer.parseInt(Jmlh2Txt.getText()) * 15000) + "\n";
        }
        if (CoklatCb.isSelected()) {
            output += "- Coklat, Harga: " + (Integer.parseInt(Jmlh3Txt.getText()) * 12000) + "\n";
        }
        if (OreoCb.isSelected()) {
            output += "- Oreo, Harga: " + (Integer.parseInt(Jmlh4Txt.getText()) * 10000) + "\n";
        }
        if (StrawberryCb.isSelected()) {
            output += "- Strawberry, Harga: " + (Integer.parseInt(Jmlh5Txt.getText()) * 15000) + "\n";
        }
        if (ManggaCb.isSelected()) {
            output += "- Mangga, Harga: " + (Integer.parseInt(Jmlh6Txt.getText()) * 10000) + "\n";
        }
        int totalHarga = 0;
        try {
            int jumlah = 0;
            String jumlahStr = Jmlh1Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (MatchaCb.isSelected()) {
                    int harga = jumlah * 20000;
                    totalHarga += harga; //totalharga = total harga(0) + harga
                }
            }

            jumlahStr = Jmlh2Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (VanillaCb.isSelected()) {
                    int harga = jumlah * 15000;
                    totalHarga += harga;
                }
            }
            jumlahStr = Jmlh3Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (CoklatCb.isSelected()) {
                    int harga = jumlah * 12000;
                    totalHarga += harga;
                }
            }
            jumlahStr = Jmlh4Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (OreoCb.isSelected()) {
                    int harga = jumlah * 10000;
                    totalHarga += harga;
                }
            }
            jumlahStr = Jmlh5Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (StrawberryCb.isSelected()) {
                    int harga = jumlah * 15000;
                    totalHarga += harga;
                }
            }
            jumlahStr = Jmlh6Txt.getText();
            if (!jumlahStr.isEmpty()) {
                jumlah = Integer.parseInt(jumlahStr);
                if (ManggaCb.isSelected()) {
                    int harga = jumlah * 10000;
                    totalHarga += harga;
                }
            }
            // Setelah menghitung totalHarga untuk semua minuman, masukkan ke output
            output += "Total Harga: " + totalHarga + "\n";

        } catch (NumberFormatException e) {
            System.out.println("Input jumlah tidak valid: " + e.getMessage());
        }

       
        
        
        OutputTxt.setText(output);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DineInCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInCbActionPerformed
        if(TakeAwayCb.isSelected()){
            TakeAwayCb.setSelected(false);
        }
    }//GEN-LAST:event_DineInCbActionPerformed
    
    private void MatchaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchaCbActionPerformed
        
    }//GEN-LAST:event_MatchaCbActionPerformed

    private void VanillaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanillaCbActionPerformed
        
    }//GEN-LAST:event_VanillaCbActionPerformed

    private void OreoCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OreoCbActionPerformed
       
    }//GEN-LAST:event_OreoCbActionPerformed

    private void StrawberryCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrawberryCbActionPerformed
       
    }//GEN-LAST:event_StrawberryCbActionPerformed

    private void ManggaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManggaCbActionPerformed
       
    }//GEN-LAST:event_ManggaCbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(OutputTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Mohon Lakukan Pengisian Pesanan Terlebih Dahulu!");
        } else {
        JOptionPane.showMessageDialog(null, "Mohon Lakukan Pembayaran Dan Tunggu Pesanan Anda. Terima Kasih!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drinks_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drinks_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drinks_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drinks_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drinks_Shop().setVisible(true);
            }
        });
    }

    // Implementasi komponen GUI dan Penamaan varibel komponen GUI ( modul 8)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CoklatCb;
    private javax.swing.JCheckBox DineInCb;
    private javax.swing.JTextField Jmlh1Txt;
    private javax.swing.JTextField Jmlh2Txt;
    private javax.swing.JTextField Jmlh3Txt;
    private javax.swing.JTextField Jmlh4Txt;
    private javax.swing.JTextField Jmlh5Txt;
    private javax.swing.JTextField Jmlh6Txt;
    private javax.swing.JCheckBox ManggaCb;
    private javax.swing.JCheckBox MatchaCb;
    private javax.swing.JTextField NamaTxt;
    private javax.swing.JCheckBox OreoCb;
    private javax.swing.JTextArea OutputTxt;
    private javax.swing.JComboBox<String> PilihMejaCbx;
    private javax.swing.JCheckBox StrawberryCb;
    private javax.swing.JCheckBox TakeAwayCb;
    private javax.swing.JCheckBox VanillaCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
